### ISSUE TITLE
Can't find init.tcl 

### ISSUE THREAD

**Issue by logic1988** [ContextLab/hypertools#218]
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    geo.plot(fmt='.')
  File "/home/usrname/.py2env/lib/python2.7/site-packages/hypertools/datageometry.py", line 189, in plot
    return plotter(d, **new_kwargs)
  File "/home/usrname/.py2env/lib/python2.7/site-packages/hypertools/plot/plot.py",
line 420, in plot
    ax=ax)
  File "/home/usrname/.py2env/lib/python2.7/site-packages/hypertools/plot/draw.py",
line 458, in _draw
    fig, ax, data = dispatch_static(x, ax)
  File "/home/usrname/.py2env/lib/python2.7/site-packages/hypertools/plot/draw.py",
line 39, in dispatch_static
    fig = plt.figure()
  File "/home/usrname/.py2env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 539, in figure
    **kwargs)
  File "/home/usrname/.py2env/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 171, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/usrname/.py2env/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/home/usrname/anaconda2/lib/python2.7/lib-tk/Tkinter.py", line 1820, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    /opt/anaconda1anaconda2anaconda3/lib/tcl8.5 /home/usrname/.py2env/lib/tcl8.5 /home/usrname/lib/tcl8.5 /home/usrname/.py2env/library /home/usrname/library /home/usrname/tcl8.5.18/library /home/tcl8.5.18/library

This probably means that Tcl wasn't installed properly.

**Comment by logic1988** [comment]
I Solved it by download tcl8.5.18 from https://sourceforge.net/projects/tcl/files/Tcl/8.5.18/tcl8.5.18-src.tar.gz/download .
