### ISSUE TITLE
roation & saving not working on large legends

### ISSUE THREAD

**Issue by flashpixx** [ContextLab/hypertools#223]
I have got a large legend of numerical data, so the legend is larger than the window size and on clicking the _save button_ an exception is thrown

```
Traceback (most recent call last):
  File "matplotlib/cbook/__init__.py", line 216, in process
    func(*args, **kwargs)
  File "hypertools/plot/draw.py", line 127, in update_position
    proj = ax.get_proj()
AttributeError: 'AxesSubplot' object has no attribute 'get_proj'
```

It would be nice, that the lgend is fit to the window size and/or the saving button works also if the legend is larger than the window

**Comment by jeremymanning** [comment]
Addressed in the HyperTools 1.0 update (PR #272, https://github.com/ContextLab/hypertools/pull/272). The label-repositioning callback (`update_position()` in `hypertools/plot/matplotlib_backend.py`) now checks `hasattr(ax, "get_proj")` before calling the 3D-only `get_proj()`/`proj3d.proj_transform`, and branches its label tuple-unpacking to match (`annotate_plot()` stores 3-tuples for 2D labels, 4-tuples for 3D), so 2D labeled plots with lots of labels no longer crash on interaction or save.

```python
import numpy as np, hypertools as hyp
from matplotlib.backend_bases import MouseEvent

data = [np.random.randn(30, 2)]
labels = [[f'label_{i}' for i in range(30)]]
fig = hyp.plot(data, labels=labels, show=False)
canvas = fig.canvas
canvas.callbacks.process('button_release_event',
                          MouseEvent('button_release_event', canvas, x=100, y=100, button=1))
fig.savefig('out.png')  # no AttributeError
```

Closing as addressed in the 1.0 update — please reopen if you hit anything else.
