### ISSUE TITLE
bug: plot_missing_data.py

### ISSUE THREAD

**Issue by andrewheusser** [ContextLab/hypertools#91]
when running plot_missing_data.py (python 2.7)

error message:
```
Traceback (most recent call last):
  File "plot_missing_data.py", line 29, in <module>
    missing_data = [inds[i] for i in np.random.choice(len(inds), len(inds)*missing)]
  File "mtrand.pyx", line 1147, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:18069)
  File "mtrand.pyx", line 979, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:16422)
  File "mtrand.pyx", line 980, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:16227)
  File "randint_helpers.pxi", line 253, in mtrand._rand_int64 (numpy/random/mtrand/mtrand.c:4193)
TypeError: 'float' object cannot be interpreted as an index
```

**Comment by andrewheusser** [comment]
also in PPCA.py - both crash on this line:

`missing_data = [inds[i] for i in np.random.choice(len(inds), len(inds)*missing)]`

**Comment by andrewheusser** [comment]
fixed on google-drive branch, will document in the 0.7.1 release notes
